version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true

environment:
  # Use Python 3.5
  PYTHON: "C:/Python35"
  SPHINXBUILD: "%PYTHON%/scripts/sphinx-build.exe"

  github_access_token:
    secure: DpN0M7pZDocpyv+muc15qHDKz9lMJ7Zr34aMC0HtOdeVkbTERuKkxq4WHAd3S33v

init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - "%PYTHON%/python.exe -m pip install --upgrade pip"

    # Install pywin32-ctypes 0.0.1 due to https://github.com/enthought/pywin32-ctypes/issues/60
    - "%PYTHON%/python.exe -m pip install pywin32-ctypes==0.0.1"

    # Install cryptography (1.8.1) to avoid 'openssl' error
    - "%PYTHON%/python.exe -m pip install cryptography==1.8.1"
    
    # Install requests (2.14.1) since msrest requires requests~=2.14.1
    - "%PYTHON%/python.exe -m pip install requests==2.14.1"

    # Install sphinx (1.5.5) and its extensions
    - "%PYTHON%/python.exe -m pip install sphinx==1.5.5"
    - "%PYTHON%/python.exe -m pip install sphinx-docfx-yaml"
    - "%PYTHON%/python.exe -m pip install sphinx_rtd_theme"
    - "%PYTHON%/python.exe -m pip show sphinx"

clone_script:
    - git config --global core.autocrlf true
    - git config core.autocrlf
    - cd c:/projects
    - git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/Azure/azure-sdk-for-python.git
    - git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/MicrosoftDocs/azure-docs-sdk-python.git

install:
    - cd c:/projects/azure-sdk-for-python

    # Ignore STDOUT
    - "%PYTHON%/python.exe setup.py install > null"

build: off

on_success:
    # remove old rst fils and copy pre-defined ref/rst
    - ps: Remove-Item c:/projects/azure-sdk-for-python/doc/ref/* -recurse
    - ps: Copy-Item c:/projects/azure-docs-sdk-python/ci_scripts/ref/*.rst -Destination c:/projects/azure-sdk-for-python/doc/ref -Recurse

    # Generate new rst files
    - cd c:/projects/azure-sdk-for-python/doc
    - ps: Copy-Item c:/projects/azure-docs-sdk-python/ci_scripts/generate_doc.py -Destination c:/projects/azure-sdk-for-python/doc/generate_doc.py
    - ps: Copy-Item c:/projects/azure-docs-sdk-python/ci_scripts/index.rst -Destination c:/projects/azure-sdk-for-python/doc/index.rst
    - "%PYTHON%/python.exe generate_doc.py"

    # Move rst file to doc path
    - ps: Move-Item c:/projects/azure-sdk-for-python/doc/ref/*.rst -Destination c:/projects/azure-sdk-for-python/doc
    
    # Generate yml
    - cd c:/projects/azure-sdk-for-python/doc
    - ps: Copy-Item c:/projects/azure-docs-sdk-python/ci_scripts/conf.py -Destination c:/projects/azure-sdk-for-python/doc/conf.py
    - ps: Copy-Item c:/projects/azure-docs-sdk-python/ci_scripts/postprocess_toc_yml.py -Destination c:/projects/azure-sdk-for-python/doc/postprocess_toc_yml.py
    - "%SPHINXBUILD% . _build"
    - "%PYTHON%/python.exe postprocess_toc_yml.py"

    # Generate xrefmap.yml
    - cd c:/projects/azure-sdk-for-python/doc
    - ps: Copy-Item c:/projects/azure-docs-sdk-python/ci_scripts/generate_xrefmap.py -Destination c:/projects/azure-sdk-for-python/doc/generate_xrefmap.py
    - "%PYTHON%/python.exe generate_xrefmap.py"

    # Fetch the latest doc then copy generated doc to c:/projects/azure-docs-sdk-python/docs-ref-autogen
    - cd c:/projects/azure-docs-sdk-python
    - git pull

    # Copy xrefmap.yml
    - ps: Copy-Item c:/projects/azure-sdk-for-python/doc/xrefmap.yml -Destination c:/projects/azure-docs-sdk-python/xrefmap.yml
    
    # remove old yml fils
    - ps: Remove-Item c:/projects/azure-docs-sdk-python/docs-ref-autogen/* -recurse

    # copy yml fils generated
    - ps: Copy-Item -Path c:/projects/azure-sdk-for-python/doc/_build/docfx_yaml/* -Destination c:/projects/azure-docs-sdk-python/docs-ref-autogen -Recurse

    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
    - git status
    - git config --global user.name "VSC-Service-Account"
    - git config --global user.email "vscavu@microsoft.com"
    - git add . > null
    - git commit -a -m "appveyor ci - update yml files" > null | echo commit change(s)

    - git push -u origin %APPVEYOR_REPO_BRANCH%:%APPVEYOR_REPO_BRANCH%

on_finish:
    # if want to RDP, uncomment below command
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
