### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.logic.models.x12_acknowledgement_settings_py3.X12AcknowledgementSettings
  fullName: azure.mgmt.logic.models.x12_acknowledgement_settings_py3.X12AcknowledgementSettings
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.logic.models.x12_acknowledgement_settings_py3
  name: X12AcknowledgementSettings
  source:
    id: X12AcknowledgementSettings
    path: azure-mgmt-logic\azure\mgmt\logic\models\x12_acknowledgement_settings_py3.py
    remote:
      branch: master
      path: azure-mgmt-logic\azure\mgmt\logic\models\x12_acknowledgement_settings_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'The X12 agreement acknowledgement settings.


    All required parameters must be populated in order to send to Azure.

    '
  syntax:
    content: 'X12AcknowledgementSettings(*, need_technical_acknowledgement: bool,
      batch_technical_acknowledgements: bool, need_functional_acknowledgement: bool,
      batch_functional_acknowledgements: bool, need_implementation_acknowledgement:
      bool, batch_implementation_acknowledgements: bool, need_loop_for_valid_messages:
      bool, send_synchronous_acknowledgement: bool, acknowledgement_control_number_lower_bound:
      int, acknowledgement_control_number_upper_bound: int, rollover_acknowledgement_control_number:
      bool, functional_acknowledgement_version: str = None, implementation_acknowledgement_version:
      str = None, acknowledgement_control_number_prefix: str = None, acknowledgement_control_number_suffix:
      str = None, **kwargs) -> None'
    parameters:
    - description: 'Required. The value indicating

        whether technical acknowledgement is needed.

        '
      id: need_technical_acknowledgement
      type:
      - bool
    - description: 'Required. The value indicating

        whether to batch the technical acknowledgements.

        '
      id: batch_technical_acknowledgements
      type:
      - bool
    - description: 'Required. The value indicating

        whether functional acknowledgement is needed.

        '
      id: need_functional_acknowledgement
      type:
      - bool
    - description: 'The functional acknowledgement

        version.

        '
      id: functional_acknowledgement_version
      type:
      - str
    - description: 'Required. The value indicating

        whether to batch functional acknowledgements.

        '
      id: batch_functional_acknowledgements
      type:
      - bool
    - description: 'Required. The value indicating

        whether implementation acknowledgement is needed.

        '
      id: need_implementation_acknowledgement
      type:
      - bool
    - description: 'The implementation

        acknowledgement version.

        '
      id: implementation_acknowledgement_version
      type:
      - str
    - description: 'Required. The value

        indicating whether to batch implementation acknowledgements.

        '
      id: batch_implementation_acknowledgements
      type:
      - bool
    - description: 'Required. The value indicating

        whether a loop is needed for valid messages.

        '
      id: need_loop_for_valid_messages
      type:
      - bool
    - description: 'Required. The value indicating

        whether to send synchronous acknowledgement.

        '
      id: send_synchronous_acknowledgement
      type:
      - bool
    - description: 'The acknowledgement control

        number prefix.

        '
      id: acknowledgement_control_number_prefix
      type:
      - str
    - description: 'The acknowledgement control

        number suffix.

        '
      id: acknowledgement_control_number_suffix
      type:
      - str
    - description: 'Required. The

        acknowledgement control number lower bound.

        '
      id: acknowledgement_control_number_lower_bound
      type:
      - int
    - description: 'Required. The

        acknowledgement control number upper bound.

        '
      id: acknowledgement_control_number_upper_bound
      type:
      - int
    - description: 'Required. The value

        indicating whether to rollover acknowledgement control number.

        '
      id: rollover_acknowledgement_control_number
      type:
      - bool
  type: class
  uid: azure.mgmt.logic.models.x12_acknowledgement_settings_py3.X12AcknowledgementSettings
references: []
