### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.resource.resources.v2018_05_01.models.deployment_extended_py3.DeploymentExtended
  fullName: azure.mgmt.resource.resources.v2018_05_01.models.deployment_extended_py3.DeploymentExtended
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.resource.resources.v2018_05_01.models.deployment_extended_py3
  name: DeploymentExtended
  source:
    id: DeploymentExtended
    path: azure-mgmt-resource\azure\mgmt\resource\resources\v2018_05_01\models\deployment_extended_py3.py
    remote:
      branch: master
      path: azure-mgmt-resource\azure\mgmt\resource\resources\v2018_05_01\models\deployment_extended_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Deployment information.


    Variables are only populated by the server, and will be ignored when

    sending a request.


    All required parameters must be populated in order to send to Azure.

    '
  syntax:
    content: 'DeploymentExtended(*, name: str, location: str = None, properties=None,
      **kwargs) -> None'
    parameters:
    - description: 'Required. The name of the deployment.

        '
      id: name
      type:
      - str
    - description: 'the location of the deployment.

        '
      id: location
      type:
      - str
    - description: 'Deployment properties.

        '
      id: properties
      type:
      - azure.mgmt.resource.resources.v2018_05_01.models.DeploymentPropertiesExtended
    variables:
    - description: 'The ID of the deployment.

        '
      id: id
      type:
      - str
  type: class
  uid: azure.mgmt.resource.resources.v2018_05_01.models.deployment_extended_py3.DeploymentExtended
references: []
