### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.resource.resources.v2017_05_10.models.deployment.Deployment
  fullName: azure.mgmt.resource.resources.v2017_05_10.models.deployment.Deployment
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.resource.resources.v2017_05_10.models.deployment
  name: Deployment
  source:
    id: Deployment
    path: azure-mgmt-resource\azure\mgmt\resource\resources\v2017_05_10\models\deployment.py
    remote:
      branch: master
      path: azure-mgmt-resource\azure\mgmt\resource\resources\v2017_05_10\models\deployment.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Deployment operation parameters.


    All required parameters must be populated in order to send to Azure.

    '
  syntax:
    content: Deployment(**kwargs)
    parameters:
    - description: 'Required. The deployment properties.

        '
      id: properties
      type:
      - azure.mgmt.resource.resources.v2017_05_10.models.DeploymentProperties
  type: class
  uid: azure.mgmt.resource.resources.v2017_05_10.models.deployment.Deployment
references: []
