### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.accepted
  - azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.canceled
  - azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.created
  - azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.creating
  - azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.deleted
  - azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.deleting
  - azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.failed
  - azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.ready
  - azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.running
  - azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.succeeded
  - azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.updating
  class: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  inheritance:
  - inheritance:
    - type: builtins.object
    type: builtins.str
  - inheritance:
    - type: builtins.object
    type: enum.Enum
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_client_enums
  name: ProvisioningState
  source:
    id: ProvisioningState
    path: azure-mgmt-resource\azure\mgmt\resource\managedapplications\models\application_client_enums.py
    remote:
      branch: master
      path: azure-mgmt-resource\azure\mgmt\resource\managedapplications\models\application_client_enums.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'An enumeration.












    '
  syntax: {}
  type: class
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
- class: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.accepted
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_client_enums
  name: accepted
  syntax:
    content: accepted = 'Accepted'
  type: attribute
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.accepted
- class: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.canceled
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_client_enums
  name: canceled
  syntax:
    content: canceled = 'Canceled'
  type: attribute
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.canceled
- class: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.created
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_client_enums
  name: created
  syntax:
    content: created = 'Created'
  type: attribute
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.created
- class: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.creating
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_client_enums
  name: creating
  syntax:
    content: creating = 'Creating'
  type: attribute
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.creating
- class: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.deleted
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_client_enums
  name: deleted
  syntax:
    content: deleted = 'Deleted'
  type: attribute
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.deleted
- class: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.deleting
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_client_enums
  name: deleting
  syntax:
    content: deleting = 'Deleting'
  type: attribute
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.deleting
- class: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.failed
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_client_enums
  name: failed
  syntax:
    content: failed = 'Failed'
  type: attribute
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.failed
- class: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.ready
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_client_enums
  name: ready
  syntax:
    content: ready = 'Ready'
  type: attribute
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.ready
- class: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.running
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_client_enums
  name: running
  syntax:
    content: running = 'Running'
  type: attribute
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.running
- class: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.succeeded
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_client_enums
  name: succeeded
  syntax:
    content: succeeded = 'Succeeded'
  type: attribute
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.succeeded
- class: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.updating
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.models.application_client_enums
  name: updating
  syntax:
    content: updating = 'Updating'
  type: attribute
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.updating
references:
- fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.accepted
  isExternal: false
  name: accepted
  parent: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.accepted
- fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.canceled
  isExternal: false
  name: canceled
  parent: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.canceled
- fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.created
  isExternal: false
  name: created
  parent: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.created
- fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.creating
  isExternal: false
  name: creating
  parent: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.creating
- fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.deleted
  isExternal: false
  name: deleted
  parent: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.deleted
- fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.deleting
  isExternal: false
  name: deleting
  parent: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.deleting
- fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.failed
  isExternal: false
  name: failed
  parent: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.failed
- fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.ready
  isExternal: false
  name: ready
  parent: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.ready
- fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.running
  isExternal: false
  name: running
  parent: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.running
- fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.succeeded
  isExternal: false
  name: succeeded
  parent: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.succeeded
- fullName: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.updating
  isExternal: false
  name: updating
  parent: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState
  uid: azure.mgmt.resource.managedapplications.models.application_client_enums.ProvisioningState.updating
