### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.rdbms.mysql.operations.configurations_operations.ConfigurationsOperations
  fullName: azure.mgmt.rdbms.mysql.operations.configurations_operations
  langs:
  - python
  module: azure.mgmt.rdbms.mysql.operations.configurations_operations
  name: configurations_operations
  source:
    id: configurations_operations
    path: azure-mgmt-rdbms\azure\mgmt\rdbms\mysql\operations\configurations_operations.py
    remote:
      branch: master
      path: azure-mgmt-rdbms\azure\mgmt\rdbms\mysql\operations\configurations_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.rdbms.mysql.operations.configurations_operations
references:
- fullName: azure.mgmt.rdbms.mysql.operations.configurations_operations.ConfigurationsOperations
  isExternal: false
  name: ConfigurationsOperations
  parent: azure.mgmt.rdbms.mysql.operations.configurations_operations
  uid: azure.mgmt.rdbms.mysql.operations.configurations_operations.ConfigurationsOperations
