### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.rdbms.mysql.my_sql_management_client.MySQLManagementClientConfiguration
  fullName: azure.mgmt.rdbms.mysql.my_sql_management_client.MySQLManagementClientConfiguration
  inheritance:
  - inheritance:
    - inheritance:
      - type: builtins.object
      type: msrest.configuration.Configuration
    type: msrestazure.azure_configuration.AzureConfiguration
  langs:
  - python
  module: azure.mgmt.rdbms.mysql.my_sql_management_client
  name: MySQLManagementClientConfiguration
  source:
    id: MySQLManagementClientConfiguration
    path: azure-mgmt-rdbms\azure\mgmt\rdbms\mysql\my_sql_management_client.py
    remote:
      branch: master
      path: azure-mgmt-rdbms\azure\mgmt\rdbms\mysql\my_sql_management_client.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 28
  summary: 'Configuration for MySQLManagementClient

    Note that all parameters used to create this instance are saved as instance

    attributes.

    '
  syntax:
    content: MySQLManagementClientConfiguration(credentials, subscription_id, base_url=None)
    parameters:
    - description: 'Credentials needed for the client to connect to Azure.

        '
      id: credentials
      type:
      - msrestazure.azure_active_directory
    - description: 'The subscription ID that identifies an Azure

        subscription.

        '
      id: subscription_id
      type:
      - str
    - description: 'Service URL

        '
      id: base_url
      type:
      - str
  type: class
  uid: azure.mgmt.rdbms.mysql.my_sql_management_client.MySQLManagementClientConfiguration
references: []
