### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.batch.models.ApplicationPackageReference
  fullName: azure.batch.models.ApplicationPackageReference
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.batch.models
  name: ApplicationPackageReference
  source:
    id: ApplicationPackageReference
    path: azure-batch\azure\batch\models\application_package_reference.py
    remote:
      branch: master
      path: azure-batch\azure\batch\models\application_package_reference.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'A reference to an application package to be deployed to compute nodes.

    '
  syntax:
    content: ApplicationPackageReference(application_id, version=None)
    parameters:
    - description: 'The ID of the application to deploy.

        '
      id: application_id
      type:
      - str
    - description: 'The version of the application to deploy. If omitted, the

        default version is deployed. If this is omitted on a pool, and no default

        version is specified for this application, the request fails with the

        error code InvalidApplicationPackageReferences and HTTP status code 409.

        If this is omitted on a task, and no default version is specified for this

        application, the task fails with a pre-processing error.

        '
      id: version
      type:
      - str
  type: class
  uid: azure.batch.models.ApplicationPackageReference
references: []
