### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.batchai.models.ssh_configuration.SshConfiguration
  fullName: azure.mgmt.batchai.models.ssh_configuration.SshConfiguration
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.batchai.models.ssh_configuration
  name: SshConfiguration
  source:
    id: SshConfiguration
    path: azure-mgmt-batchai\azure\mgmt\batchai\models\ssh_configuration.py
    remote:
      branch: master
      path: azure-mgmt-batchai\azure\mgmt\batchai\models\ssh_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'SSH configuration settings for the VM.


    All required parameters must be populated in order to send to Azure.

    '
  syntax:
    content: SshConfiguration(**kwargs)
    parameters:
    - description: 'List of source IP ranges to allow SSH

        connection to a node. Default value is ''*'' can be used to match all source

        IPs. Maximum number of IP ranges that can be specified are 400.

        '
      id: public_ips_to_allow
      type:
      - list[str]
    - description: 'Required. Settings for user account to be

        created on a node.

        '
      id: user_account_settings
      type:
      - azure.mgmt.batchai.models.UserAccountSettings
  type: class
  uid: azure.mgmt.batchai.models.ssh_configuration.SshConfiguration
references:
- fullName: list[str]
  name: list[str]
  spec.python:
  - fullName: list
    name: list
    uid: list
  - fullName: '['
    name: '['
  - fullName: str
    name: str
    uid: str
  - fullName: ']'
    name: ']'
  uid: list[str]
