### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.media.models.streaming_policy_play_ready_configuration_py3.StreamingPolicyPlayReadyConfiguration
  fullName: azure.mgmt.media.models.streaming_policy_play_ready_configuration_py3.StreamingPolicyPlayReadyConfiguration
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.media.models.streaming_policy_play_ready_configuration_py3
  name: StreamingPolicyPlayReadyConfiguration
  source:
    id: StreamingPolicyPlayReadyConfiguration
    path: azure-mgmt-media\azure\mgmt\media\models\streaming_policy_play_ready_configuration_py3.py
    remote:
      branch: master
      path: azure-mgmt-media\azure\mgmt\media\models\streaming_policy_play_ready_configuration_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Class to specify configurations of PlayReady in Streaming Policy.

    '
  syntax:
    content: 'StreamingPolicyPlayReadyConfiguration(*, custom_license_acquisition_url_template:
      str = None, play_ready_custom_attributes: str = None, **kwargs) -> None'
    parameters:
    - description: 'The template for a

        customer service to deliver keys to end users.  Not needed when using

        Azure Media Services for issuing keys.

        '
      id: custom_license_acquisition_url_template
      type:
      - str
    - description: 'Custom attributes for PlayReady

        '
      id: play_ready_custom_attributes
      type:
      - str
  type: class
  uid: azure.mgmt.media.models.streaming_policy_play_ready_configuration_py3.StreamingPolicyPlayReadyConfiguration
references: []
