### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.network.v2018_06_01.models.bgp_settings.BgpSettings
  fullName: azure.mgmt.network.v2018_06_01.models.bgp_settings.BgpSettings
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.network.v2018_06_01.models.bgp_settings
  name: BgpSettings
  source:
    id: BgpSettings
    path: azure-mgmt-network\azure\mgmt\network\v2018_06_01\models\bgp_settings.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2018_06_01\models\bgp_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'BGP settings details.

    '
  syntax:
    content: BgpSettings(**kwargs)
    parameters:
    - description: 'The BGP speaker''s ASN.

        '
      id: asn
      type:
      - long
    - description: 'The BGP peering address and BGP identifier of

        this BGP speaker.

        '
      id: bgp_peering_address
      type:
      - str
    - description: 'The weight added to routes learned from this BGP

        speaker.

        '
      id: peer_weight
      type:
      - int
  type: class
  uid: azure.mgmt.network.v2018_06_01.models.bgp_settings.BgpSettings
references: []
