### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.network.v2017_06_01.models.ipv6_express_route_circuit_peering_config_py3.Ipv6ExpressRouteCircuitPeeringConfig
  fullName: azure.mgmt.network.v2017_06_01.models.ipv6_express_route_circuit_peering_config_py3
  langs:
  - python
  module: azure.mgmt.network.v2017_06_01.models.ipv6_express_route_circuit_peering_config_py3
  name: ipv6_express_route_circuit_peering_config_py3
  source:
    id: ipv6_express_route_circuit_peering_config_py3
    path: azure-mgmt-network\azure\mgmt\network\v2017_06_01\models\ipv6_express_route_circuit_peering_config_py3.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2017_06_01\models\ipv6_express_route_circuit_peering_config_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.network.v2017_06_01.models.ipv6_express_route_circuit_peering_config_py3
references:
- fullName: azure.mgmt.network.v2017_06_01.models.ipv6_express_route_circuit_peering_config_py3.Ipv6ExpressRouteCircuitPeeringConfig
  isExternal: false
  name: Ipv6ExpressRouteCircuitPeeringConfig
  parent: azure.mgmt.network.v2017_06_01.models.ipv6_express_route_circuit_peering_config_py3
  uid: azure.mgmt.network.v2017_06_01.models.ipv6_express_route_circuit_peering_config_py3.Ipv6ExpressRouteCircuitPeeringConfig
