### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.network.v2018_06_01.models.protocol_configuration.ProtocolConfiguration
  fullName: azure.mgmt.network.v2018_06_01.models.protocol_configuration
  langs:
  - python
  module: azure.mgmt.network.v2018_06_01.models.protocol_configuration
  name: protocol_configuration
  source:
    id: protocol_configuration
    path: azure-mgmt-network\azure\mgmt\network\v2018_06_01\models\protocol_configuration.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2018_06_01\models\protocol_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.network.v2018_06_01.models.protocol_configuration
references:
- fullName: azure.mgmt.network.v2018_06_01.models.protocol_configuration.ProtocolConfiguration
  isExternal: false
  name: ProtocolConfiguration
  parent: azure.mgmt.network.v2018_06_01.models.protocol_configuration
  uid: azure.mgmt.network.v2018_06_01.models.protocol_configuration.ProtocolConfiguration
