### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.network.v2016_09_01.models.application_gateway_ip_configuration_py3.ApplicationGatewayIPConfiguration
  fullName: azure.mgmt.network.v2016_09_01.models.application_gateway_ip_configuration_py3.ApplicationGatewayIPConfiguration
  inheritance:
  - inheritance:
    - inheritance:
      - type: builtins.object
      type: msrest.serialization.Model
    type: azure.mgmt.network.v2016_09_01.models.sub_resource_py3.SubResource
  langs:
  - python
  module: azure.mgmt.network.v2016_09_01.models.application_gateway_ip_configuration_py3
  name: ApplicationGatewayIPConfiguration
  source:
    id: ApplicationGatewayIPConfiguration
    path: azure-mgmt-network\azure\mgmt\network\v2016_09_01\models\application_gateway_ip_configuration_py3.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2016_09_01\models\application_gateway_ip_configuration_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'IP configuration of an application gateway. Currently 1 public and 1

    private IP configuration is allowed.

    '
  syntax:
    content: 'ApplicationGatewayIPConfiguration(*, id: str = None, subnet=None, provisioning_state:
      str = None, name: str = None, etag: str = None, **kwargs) -> None'
    parameters:
    - description: 'Resource ID.

        '
      id: id
      type:
      - str
    - description: 'Reference of the subnet resource. A subnet from where

        application gateway gets its private address.

        '
      id: subnet
      type:
      - azure.mgmt.network.v2016_09_01.models.SubResource
    - description: 'Provisioning state of the application gateway

        subnet resource. Possible values are: ''Updating'', ''Deleting'', and

        ''Failed''.

        '
      id: provisioning_state
      type:
      - str
    - description: 'Name of the resource that is unique within a resource group.

        This name can be used to access the resource.

        '
      id: name
      type:
      - str
    - description: 'A unique read-only string that changes whenever the resource

        is updated.

        '
      id: etag
      type:
      - str
  type: class
  uid: azure.mgmt.network.v2016_09_01.models.application_gateway_ip_configuration_py3.ApplicationGatewayIPConfiguration
references: []
