### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.network.v2017_10_01.operations.application_security_groups_operations.ApplicationSecurityGroupsOperations
  fullName: azure.mgmt.network.v2017_10_01.operations.application_security_groups_operations
  langs:
  - python
  module: azure.mgmt.network.v2017_10_01.operations.application_security_groups_operations
  name: application_security_groups_operations
  source:
    id: application_security_groups_operations
    path: azure-mgmt-network\azure\mgmt\network\v2017_10_01\operations\application_security_groups_operations.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2017_10_01\operations\application_security_groups_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.network.v2017_10_01.operations.application_security_groups_operations
references:
- fullName: azure.mgmt.network.v2017_10_01.operations.application_security_groups_operations.ApplicationSecurityGroupsOperations
  isExternal: false
  name: ApplicationSecurityGroupsOperations
  parent: azure.mgmt.network.v2017_10_01.operations.application_security_groups_operations
  uid: azure.mgmt.network.v2017_10_01.operations.application_security_groups_operations.ApplicationSecurityGroupsOperations
