### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.network.v2017_08_01.models.BgpSettings
  fullName: azure.mgmt.network.v2017_08_01.models.BgpSettings
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.network.v2017_08_01.models
  name: BgpSettings
  source:
    id: BgpSettings
    path: azure-mgmt-network\azure\mgmt\network\v2017_08_01\models\bgp_settings_py3.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2017_08_01\models\bgp_settings_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'BGP settings details.

    '
  syntax:
    content: 'BgpSettings(*, asn: int = None, bgp_peering_address: str = None, peer_weight:
      int = None, **kwargs) -> None'
    parameters:
    - description: 'The BGP speaker''s ASN.

        '
      id: asn
      type:
      - long
    - description: 'The BGP peering address and BGP identifier of

        this BGP speaker.

        '
      id: bgp_peering_address
      type:
      - str
    - description: 'The weight added to routes learned from this BGP

        speaker.

        '
      id: peer_weight
      type:
      - int
  type: class
  uid: azure.mgmt.network.v2017_08_01.models.BgpSettings
references: []
