### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.network.v2018_04_01.models.application_gateway_autoscale_configuration.ApplicationGatewayAutoscaleConfiguration
  fullName: azure.mgmt.network.v2018_04_01.models.application_gateway_autoscale_configuration
  langs:
  - python
  module: azure.mgmt.network.v2018_04_01.models.application_gateway_autoscale_configuration
  name: application_gateway_autoscale_configuration
  source:
    id: application_gateway_autoscale_configuration
    path: azure-mgmt-network\azure\mgmt\network\v2018_04_01\models\application_gateway_autoscale_configuration.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2018_04_01\models\application_gateway_autoscale_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.network.v2018_04_01.models.application_gateway_autoscale_configuration
references:
- fullName: azure.mgmt.network.v2018_04_01.models.application_gateway_autoscale_configuration.ApplicationGatewayAutoscaleConfiguration
  isExternal: false
  name: ApplicationGatewayAutoscaleConfiguration
  parent: azure.mgmt.network.v2018_04_01.models.application_gateway_autoscale_configuration
  uid: azure.mgmt.network.v2018_04_01.models.application_gateway_autoscale_configuration.ApplicationGatewayAutoscaleConfiguration
