### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.network.v2018_04_01.models.vpn_client_configuration.VpnClientConfiguration
  fullName: azure.mgmt.network.v2018_04_01.models.vpn_client_configuration.VpnClientConfiguration
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.network.v2018_04_01.models.vpn_client_configuration
  name: VpnClientConfiguration
  source:
    id: VpnClientConfiguration
    path: azure-mgmt-network\azure\mgmt\network\v2018_04_01\models\vpn_client_configuration.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2018_04_01\models\vpn_client_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'VpnClientConfiguration for P2S client.

    '
  syntax:
    content: VpnClientConfiguration(**kwargs)
    parameters:
    - description: 'The reference of the address space

        resource which represents Address space for P2S VpnClient.

        '
      id: vpn_client_address_pool
      type:
      - azure.mgmt.network.v2018_04_01.models.AddressSpace
    - description: 'VpnClientRootCertificate for virtual

        network gateway.

        '
      id: vpn_client_root_certificates
      type:
      - list[azure.mgmt.network.v2018_04_01.models.VpnClientRootCertificate]
    - description: 'VpnClientRevokedCertificate for

        Virtual network gateway.

        '
      id: vpn_client_revoked_certificates
      type:
      - list[azure.mgmt.network.v2018_04_01.models.VpnClientRevokedCertificate]
    - description: 'VpnClientProtocols for Virtual network

        gateway.

        '
      id: vpn_client_protocols
      type:
      - list[str
      - azure.mgmt.network.v2018_04_01.models.VpnClientProtocol]
    - description: 'VpnClientIpsecPolicies for virtual

        network gateway P2S client.

        '
      id: vpn_client_ipsec_policies
      type:
      - list[azure.mgmt.network.v2018_04_01.models.IpsecPolicy]
    - description: 'The radius server address property of the

        VirtualNetworkGateway resource for vpn client connection.

        '
      id: radius_server_address
      type:
      - str
    - description: 'The radius secret property of the

        VirtualNetworkGateway resource for vpn client connection.

        '
      id: radius_server_secret
      type:
      - str
  type: class
  uid: azure.mgmt.network.v2018_04_01.models.vpn_client_configuration.VpnClientConfiguration
references:
- fullName: list[azure.mgmt.network.v2018_04_01.models.VpnClientRootCertificate]
  name: list[VpnClientRootCertificate]
  spec.python:
  - fullName: list
    name: list
    uid: list
  - fullName: '['
    name: '['
  - fullName: azure.mgmt.network.v2018_04_01.models.VpnClientRootCertificate
    name: VpnClientRootCertificate
    uid: azure.mgmt.network.v2018_04_01.models.VpnClientRootCertificate
  - fullName: ']'
    name: ']'
  uid: list[azure.mgmt.network.v2018_04_01.models.VpnClientRootCertificate]
- fullName: list[azure.mgmt.network.v2018_04_01.models.VpnClientRevokedCertificate]
  name: list[VpnClientRevokedCertificate]
  spec.python:
  - fullName: list
    name: list
    uid: list
  - fullName: '['
    name: '['
  - fullName: azure.mgmt.network.v2018_04_01.models.VpnClientRevokedCertificate
    name: VpnClientRevokedCertificate
    uid: azure.mgmt.network.v2018_04_01.models.VpnClientRevokedCertificate
  - fullName: ']'
    name: ']'
  uid: list[azure.mgmt.network.v2018_04_01.models.VpnClientRevokedCertificate]
- fullName: list[str
  name: list[str
  spec.python:
  - fullName: list
    name: list
    uid: list
  - fullName: '['
    name: '['
  - fullName: str
    name: str
    uid: str
  uid: list[str
- fullName: azure.mgmt.network.v2018_04_01.models.VpnClientProtocol]
  name: VpnClientProtocol]
  spec.python:
  - fullName: azure.mgmt.network.v2018_04_01.models.VpnClientProtocol
    name: VpnClientProtocol
    uid: azure.mgmt.network.v2018_04_01.models.VpnClientProtocol
  - fullName: ']'
    name: ']'
  uid: azure.mgmt.network.v2018_04_01.models.VpnClientProtocol]
- fullName: list[azure.mgmt.network.v2018_04_01.models.IpsecPolicy]
  name: list[IpsecPolicy]
  spec.python:
  - fullName: list
    name: list
    uid: list
  - fullName: '['
    name: '['
  - fullName: azure.mgmt.network.v2018_04_01.models.IpsecPolicy
    name: IpsecPolicy
    uid: azure.mgmt.network.v2018_04_01.models.IpsecPolicy
  - fullName: ']'
    name: ']'
  uid: list[azure.mgmt.network.v2018_04_01.models.IpsecPolicy]
