### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.network.v2018_04_01.models.get_vpn_sites_configuration_request.GetVpnSitesConfigurationRequest
  fullName: azure.mgmt.network.v2018_04_01.models.get_vpn_sites_configuration_request
  langs:
  - python
  module: azure.mgmt.network.v2018_04_01.models.get_vpn_sites_configuration_request
  name: get_vpn_sites_configuration_request
  source:
    id: get_vpn_sites_configuration_request
    path: azure-mgmt-network\azure\mgmt\network\v2018_04_01\models\get_vpn_sites_configuration_request.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2018_04_01\models\get_vpn_sites_configuration_request.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.network.v2018_04_01.models.get_vpn_sites_configuration_request
references:
- fullName: azure.mgmt.network.v2018_04_01.models.get_vpn_sites_configuration_request.GetVpnSitesConfigurationRequest
  isExternal: false
  name: GetVpnSitesConfigurationRequest
  parent: azure.mgmt.network.v2018_04_01.models.get_vpn_sites_configuration_request
  uid: azure.mgmt.network.v2018_04_01.models.get_vpn_sites_configuration_request.GetVpnSitesConfigurationRequest
