### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.network.v2018_06_01.models.azure_firewall_application_rule_collection.AzureFirewallApplicationRuleCollection
  fullName: azure.mgmt.network.v2018_06_01.models.azure_firewall_application_rule_collection
  langs:
  - python
  module: azure.mgmt.network.v2018_06_01.models.azure_firewall_application_rule_collection
  name: azure_firewall_application_rule_collection
  source:
    id: azure_firewall_application_rule_collection
    path: azure-mgmt-network\azure\mgmt\network\v2018_06_01\models\azure_firewall_application_rule_collection.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2018_06_01\models\azure_firewall_application_rule_collection.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.network.v2018_06_01.models.azure_firewall_application_rule_collection
references:
- fullName: azure.mgmt.network.v2018_06_01.models.azure_firewall_application_rule_collection.AzureFirewallApplicationRuleCollection
  isExternal: false
  name: AzureFirewallApplicationRuleCollection
  parent: azure.mgmt.network.v2018_06_01.models.azure_firewall_application_rule_collection
  uid: azure.mgmt.network.v2018_06_01.models.azure_firewall_application_rule_collection.AzureFirewallApplicationRuleCollection
