### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.network.v2018_06_01.models.http_configuration.HTTPConfiguration
  fullName: azure.mgmt.network.v2018_06_01.models.http_configuration
  langs:
  - python
  module: azure.mgmt.network.v2018_06_01.models.http_configuration
  name: http_configuration
  source:
    id: http_configuration
    path: azure-mgmt-network\azure\mgmt\network\v2018_06_01\models\http_configuration.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2018_06_01\models\http_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.network.v2018_06_01.models.http_configuration
references:
- fullName: azure.mgmt.network.v2018_06_01.models.http_configuration.HTTPConfiguration
  isExternal: false
  name: HTTPConfiguration
  parent: azure.mgmt.network.v2018_06_01.models.http_configuration
  uid: azure.mgmt.network.v2018_06_01.models.http_configuration.HTTPConfiguration
