### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.compute.v2016_04_30_preview.models.encryption_settings.EncryptionSettings
  fullName: azure.mgmt.compute.v2016_04_30_preview.models.encryption_settings
  langs:
  - python
  module: azure.mgmt.compute.v2016_04_30_preview.models.encryption_settings
  name: encryption_settings
  source:
    id: encryption_settings
    path: azure-mgmt-compute\azure\mgmt\compute\v2016_04_30_preview\models\encryption_settings.py
    remote:
      branch: master
      path: azure-mgmt-compute\azure\mgmt\compute\v2016_04_30_preview\models\encryption_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.compute.v2016_04_30_preview.models.encryption_settings
references:
- fullName: azure.mgmt.compute.v2016_04_30_preview.models.encryption_settings.EncryptionSettings
  isExternal: false
  name: EncryptionSettings
  parent: azure.mgmt.compute.v2016_04_30_preview.models.encryption_settings
  uid: azure.mgmt.compute.v2016_04_30_preview.models.encryption_settings.EncryptionSettings
