### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_network_configuration.VirtualMachineScaleSetUpdateNetworkConfiguration
  fullName: azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_network_configuration
  langs:
  - python
  module: azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_network_configuration
  name: virtual_machine_scale_set_update_network_configuration
  source:
    id: virtual_machine_scale_set_update_network_configuration
    path: azure-mgmt-compute\azure\mgmt\compute\v2017_03_30\models\virtual_machine_scale_set_update_network_configuration.py
    remote:
      branch: master
      path: azure-mgmt-compute\azure\mgmt\compute\v2017_03_30\models\virtual_machine_scale_set_update_network_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_network_configuration
references:
- fullName: azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_network_configuration.VirtualMachineScaleSetUpdateNetworkConfiguration
  isExternal: false
  name: VirtualMachineScaleSetUpdateNetworkConfiguration
  parent: azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_network_configuration
  uid: azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_network_configuration.VirtualMachineScaleSetUpdateNetworkConfiguration
