### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.compute.v2018_06_01.models.recommended_machine_configuration.RecommendedMachineConfiguration
  fullName: azure.mgmt.compute.v2018_06_01.models.recommended_machine_configuration
  langs:
  - python
  module: azure.mgmt.compute.v2018_06_01.models.recommended_machine_configuration
  name: recommended_machine_configuration
  source:
    id: recommended_machine_configuration
    path: azure-mgmt-compute\azure\mgmt\compute\v2018_06_01\models\recommended_machine_configuration.py
    remote:
      branch: master
      path: azure-mgmt-compute\azure\mgmt\compute\v2018_06_01\models\recommended_machine_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.compute.v2018_06_01.models.recommended_machine_configuration
references:
- fullName: azure.mgmt.compute.v2018_06_01.models.recommended_machine_configuration.RecommendedMachineConfiguration
  isExternal: false
  name: RecommendedMachineConfiguration
  parent: azure.mgmt.compute.v2018_06_01.models.recommended_machine_configuration
  uid: azure.mgmt.compute.v2018_06_01.models.recommended_machine_configuration.RecommendedMachineConfiguration
