### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.compute.v2016_04_30_preview.models.linux_configuration_py3.LinuxConfiguration
  fullName: azure.mgmt.compute.v2016_04_30_preview.models.linux_configuration_py3
  langs:
  - python
  module: azure.mgmt.compute.v2016_04_30_preview.models.linux_configuration_py3
  name: linux_configuration_py3
  source:
    id: linux_configuration_py3
    path: azure-mgmt-compute\azure\mgmt\compute\v2016_04_30_preview\models\linux_configuration_py3.py
    remote:
      branch: master
      path: azure-mgmt-compute\azure\mgmt\compute\v2016_04_30_preview\models\linux_configuration_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.compute.v2016_04_30_preview.models.linux_configuration_py3
references:
- fullName: azure.mgmt.compute.v2016_04_30_preview.models.linux_configuration_py3.LinuxConfiguration
  isExternal: false
  name: LinuxConfiguration
  parent: azure.mgmt.compute.v2016_04_30_preview.models.linux_configuration_py3
  uid: azure.mgmt.compute.v2016_04_30_preview.models.linux_configuration_py3.LinuxConfiguration
