### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.containerinstance.models.environment_variable_py3.EnvironmentVariable
  fullName: azure.mgmt.containerinstance.models.environment_variable_py3
  langs:
  - python
  module: azure.mgmt.containerinstance.models.environment_variable_py3
  name: environment_variable_py3
  source:
    id: environment_variable_py3
    path: azure-mgmt-containerinstance\azure\mgmt\containerinstance\models\environment_variable_py3.py
    remote:
      branch: master
      path: azure-mgmt-containerinstance\azure\mgmt\containerinstance\models\environment_variable_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.containerinstance.models.environment_variable_py3
references:
- fullName: azure.mgmt.containerinstance.models.environment_variable_py3.EnvironmentVariable
  isExternal: false
  name: EnvironmentVariable
  parent: azure.mgmt.containerinstance.models.environment_variable_py3
  uid: azure.mgmt.containerinstance.models.environment_variable_py3.EnvironmentVariable
