### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.servicefabric.models.wait_for_reconfiguration_safety_check_py3.WaitForReconfigurationSafetyCheck
  fullName: azure.servicefabric.models.wait_for_reconfiguration_safety_check_py3.WaitForReconfigurationSafetyCheck
  inheritance:
  - inheritance:
    - inheritance:
      - inheritance:
        - type: builtins.object
        type: msrest.serialization.Model
      type: azure.servicefabric.models.safety_check_py3.SafetyCheck
    type: azure.servicefabric.models.partition_safety_check_py3.PartitionSafetyCheck
  langs:
  - python
  module: azure.servicefabric.models.wait_for_reconfiguration_safety_check_py3
  name: WaitForReconfigurationSafetyCheck
  source:
    id: WaitForReconfigurationSafetyCheck
    path: azure-servicefabric\azure\servicefabric\models\wait_for_reconfiguration_safety_check_py3.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\wait_for_reconfiguration_safety_check_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Safety check that waits for the current reconfiguration of the partition
    to

    be completed before starting an upgrade.


    All required parameters must be populated in order to send to Azure.

    '
  syntax:
    content: 'WaitForReconfigurationSafetyCheck(*, partition_id: str = None, **kwargs)
      -> None'
    parameters:
    - description: 'Required. Constant filled by server.

        '
      id: kind
      type:
      - str
    - description: 'Id of the partition which is undergoing the safety

        check.

        '
      id: partition_id
      type:
      - str
  type: class
  uid: azure.servicefabric.models.wait_for_reconfiguration_safety_check_py3.WaitForReconfigurationSafetyCheck
references: []
