### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.available
  - azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.failed
  - azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.invalid
  - azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.provisioning
  - azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.unprovisioning
  class: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
  fullName: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
  inheritance:
  - inheritance:
    - type: builtins.object
    type: builtins.str
  - inheritance:
    - type: builtins.object
    type: enum.Enum
  langs:
  - python
  module: azure.servicefabric.models.service_fabric_client_ap_is_enums
  name: ApplicationTypeStatus
  source:
    id: ApplicationTypeStatus
    path: azure-servicefabric\azure\servicefabric\models\service_fabric_client_ap_is_enums.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\service_fabric_client_ap_is_enums.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 56
  summary: 'An enumeration.






    '
  syntax: {}
  type: class
  uid: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
- class: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
  fullName: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.available
  langs:
  - python
  module: azure.servicefabric.models.service_fabric_client_ap_is_enums
  name: available
  source:
    id: available
    path: null
    remote:
      branch: master
      path: null
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: null
  summary: 'Indicates that the application type is fully provisioned and is available
    for use. An application of this type and version can be created. The value is
    2.

    '
  syntax:
    content: available = 'Available'
  type: attribute
  uid: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.available
- class: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
  fullName: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.failed
  langs:
  - python
  module: azure.servicefabric.models.service_fabric_client_ap_is_enums
  name: failed
  source:
    id: failed
    path: null
    remote:
      branch: master
      path: null
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: null
  summary: 'Indicates that the application type provisioning failed and it is unavailable
    for use. The failure details can be obtained from the application type information
    query. The failed application type information remains in the cluster until it
    is unprovisioned or reprovisioned successfully. The value is 4.

    '
  syntax:
    content: failed = 'Failed'
  type: attribute
  uid: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.failed
- class: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
  fullName: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.invalid
  langs:
  - python
  module: azure.servicefabric.models.service_fabric_client_ap_is_enums
  name: invalid
  source:
    id: invalid
    path: null
    remote:
      branch: master
      path: null
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: null
  summary: 'Indicates the application type status is invalid. All Service Fabric enumerations
    have the invalid type. The value is zero.

    '
  syntax:
    content: invalid = 'Invalid'
  type: attribute
  uid: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.invalid
- class: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
  fullName: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.provisioning
  langs:
  - python
  module: azure.servicefabric.models.service_fabric_client_ap_is_enums
  name: provisioning
  source:
    id: provisioning
    path: null
    remote:
      branch: master
      path: null
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: null
  summary: 'Indicates that the application type is being provisioned in the cluster.
    The value is 1.

    '
  syntax:
    content: provisioning = 'Provisioning'
  type: attribute
  uid: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.provisioning
- class: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
  fullName: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.unprovisioning
  langs:
  - python
  module: azure.servicefabric.models.service_fabric_client_ap_is_enums
  name: unprovisioning
  source:
    id: unprovisioning
    path: null
    remote:
      branch: master
      path: null
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: null
  summary: 'Indicates that the application type is in process of being unprovisioned
    from the cluster. The value is 3.

    '
  syntax:
    content: unprovisioning = 'Unprovisioning'
  type: attribute
  uid: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.unprovisioning
references:
- fullName: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.available
  isExternal: false
  name: available
  parent: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
  uid: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.available
- fullName: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.failed
  isExternal: false
  name: failed
  parent: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
  uid: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.failed
- fullName: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.invalid
  isExternal: false
  name: invalid
  parent: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
  uid: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.invalid
- fullName: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.provisioning
  isExternal: false
  name: provisioning
  parent: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
  uid: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.provisioning
- fullName: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.unprovisioning
  isExternal: false
  name: unprovisioning
  parent: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus
  uid: azure.servicefabric.models.service_fabric_client_ap_is_enums.ApplicationTypeStatus.unprovisioning
