### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.batchai.models.custom_toolkit_settings.CustomToolkitSettings
  fullName: azure.mgmt.batchai.models.custom_toolkit_settings
  langs:
  - python
  module: azure.mgmt.batchai.models.custom_toolkit_settings
  name: custom_toolkit_settings
  source:
    id: custom_toolkit_settings
    path: azure-mgmt-batchai\azure\mgmt\batchai\models\custom_toolkit_settings.py
    remote:
      branch: master
      path: azure-mgmt-batchai\azure\mgmt\batchai\models\custom_toolkit_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.batchai.models.custom_toolkit_settings
references:
- fullName: azure.mgmt.batchai.models.custom_toolkit_settings.CustomToolkitSettings
  isExternal: false
  name: CustomToolkitSettings
  parent: azure.mgmt.batchai.models.custom_toolkit_settings
  uid: azure.mgmt.batchai.models.custom_toolkit_settings.CustomToolkitSettings
