### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.web.models.FileSystemApplicationLogsConfig
  fullName: azure.mgmt.web.models.FileSystemApplicationLogsConfig
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.web.models
  name: FileSystemApplicationLogsConfig
  source:
    id: FileSystemApplicationLogsConfig
    path: azure-mgmt-web\azure\mgmt\web\models\file_system_application_logs_config.py
    remote:
      branch: master
      path: azure-mgmt-web\azure\mgmt\web\models\file_system_application_logs_config.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Application logs to file system configuration.

    '
  syntax:
    content: FileSystemApplicationLogsConfig(level='Off')
    parameters:
    - description: 'Log level. Possible values include: ''Off'', ''Verbose'',

        ''Information'', ''Warning'', ''Error''. Default value: "Off" .

        '
      id: level
      type:
      - str
      - azure.mgmt.web.models.LogLevel
  type: class
  uid: azure.mgmt.web.models.FileSystemApplicationLogsConfig
references: []
