### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.compute.v2018_04_01.models.disk_encryption_settings.DiskEncryptionSettings
  fullName: azure.mgmt.compute.v2018_04_01.models.disk_encryption_settings
  langs:
  - python
  module: azure.mgmt.compute.v2018_04_01.models.disk_encryption_settings
  name: disk_encryption_settings
  source:
    id: disk_encryption_settings
    path: azure-mgmt-compute\azure\mgmt\compute\v2018_04_01\models\disk_encryption_settings.py
    remote:
      branch: master
      path: azure-mgmt-compute\azure\mgmt\compute\v2018_04_01\models\disk_encryption_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.compute.v2018_04_01.models.disk_encryption_settings
references:
- fullName: azure.mgmt.compute.v2018_04_01.models.disk_encryption_settings.DiskEncryptionSettings
  isExternal: false
  name: DiskEncryptionSettings
  parent: azure.mgmt.compute.v2018_04_01.models.disk_encryption_settings
  uid: azure.mgmt.compute.v2018_04_01.models.disk_encryption_settings.DiskEncryptionSettings
