### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.compute.v2016_03_30.models.linux_configuration.LinuxConfiguration
  fullName: azure.mgmt.compute.v2016_03_30.models.linux_configuration
  langs:
  - python
  module: azure.mgmt.compute.v2016_03_30.models.linux_configuration
  name: linux_configuration
  source:
    id: linux_configuration
    path: azure-mgmt-compute\azure\mgmt\compute\v2016_03_30\models\linux_configuration.py
    remote:
      branch: master
      path: azure-mgmt-compute\azure\mgmt\compute\v2016_03_30\models\linux_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.compute.v2016_03_30.models.linux_configuration
references:
- fullName: azure.mgmt.compute.v2016_03_30.models.linux_configuration.LinuxConfiguration
  isExternal: false
  name: LinuxConfiguration
  parent: azure.mgmt.compute.v2016_03_30.models.linux_configuration
  uid: azure.mgmt.compute.v2016_03_30.models.linux_configuration.LinuxConfiguration
