### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_ip_configuration_py3.VirtualMachineScaleSetUpdateIPConfiguration
  fullName: azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_ip_configuration_py3
  langs:
  - python
  module: azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_ip_configuration_py3
  name: virtual_machine_scale_set_update_ip_configuration_py3
  source:
    id: virtual_machine_scale_set_update_ip_configuration_py3
    path: azure-mgmt-compute\azure\mgmt\compute\v2017_03_30\models\virtual_machine_scale_set_update_ip_configuration_py3.py
    remote:
      branch: master
      path: azure-mgmt-compute\azure\mgmt\compute\v2017_03_30\models\virtual_machine_scale_set_update_ip_configuration_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_ip_configuration_py3
references:
- fullName: azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_ip_configuration_py3.VirtualMachineScaleSetUpdateIPConfiguration
  isExternal: false
  name: VirtualMachineScaleSetUpdateIPConfiguration
  parent: azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_ip_configuration_py3
  uid: azure.mgmt.compute.v2017_03_30.models.virtual_machine_scale_set_update_ip_configuration_py3.VirtualMachineScaleSetUpdateIPConfiguration
