### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.servicefabric.models.application_resource_list.ApplicationResourceList
  fullName: azure.mgmt.servicefabric.models.application_resource_list
  langs:
  - python
  module: azure.mgmt.servicefabric.models.application_resource_list
  name: application_resource_list
  source:
    id: application_resource_list
    path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\application_resource_list.py
    remote:
      branch: master
      path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\application_resource_list.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.servicefabric.models.application_resource_list
references:
- fullName: azure.mgmt.servicefabric.models.application_resource_list.ApplicationResourceList
  isExternal: false
  name: ApplicationResourceList
  parent: azure.mgmt.servicefabric.models.application_resource_list
  uid: azure.mgmt.servicefabric.models.application_resource_list.ApplicationResourceList
