### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.batch.models.CloudServiceConfiguration
  fullName: azure.mgmt.batch.models.CloudServiceConfiguration
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.batch.models
  name: CloudServiceConfiguration
  source:
    id: CloudServiceConfiguration
    path: azure-mgmt-batch\azure\mgmt\batch\models\cloud_service_configuration.py
    remote:
      branch: master
      path: azure-mgmt-batch\azure\mgmt\batch\models\cloud_service_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'The configuration for nodes in a pool based on the Azure Cloud Services

    platform.

    '
  syntax:
    content: CloudServiceConfiguration(os_family, target_os_version=None, current_os_version=None)
    parameters:
    - description: 'The Azure Guest OS family to be installed on the virtual

        machines in the pool. Possible values are: 2 - OS Family 2, equivalent to

        Windows Server 2008 R2 SP1. 3 - OS Family 3, equivalent to Windows Server

        2012. 4 - OS Family 4, equivalent to Windows Server 2012 R2. 5 - OS Family

        5, equivalent to Windows Server 2016. For more information, see Azure

        Guest OS Releases

        ([https://azure.microsoft.com/documentation/articles/cloud-services-guestos-update-matrix/#releases](https://azure.microsoft.com/documentation/articles/cloud-services-guestos-update-matrix/#releases)).

        '
      id: os_family
      type:
      - str
    - description: 'The Azure Guest OS version to be installed on

        the virtual machines in the pool. The default value is * which specifies

        the latest operating system version for the specified OS family.

        '
      id: target_os_version
      type:
      - str
    - description: 'The Azure Guest OS Version currently installed

        on the virtual machines in the pool. This may differ from targetOSVersion

        if the pool state is Upgrading. In this case some virtual machines may be

        on the targetOSVersion and some may be on the currentOSVersion during the

        upgrade process. Once all virtual machines have upgraded, currentOSVersion

        is updated to be the same as targetOSVersion.

        '
      id: current_os_version
      type:
      - str
  type: class
  uid: azure.mgmt.batch.models.CloudServiceConfiguration
references: []
