### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.servicefabric.models.application_parameter_py3.ApplicationParameter
  fullName: azure.mgmt.servicefabric.models.application_parameter_py3.ApplicationParameter
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.servicefabric.models.application_parameter_py3
  name: ApplicationParameter
  source:
    id: ApplicationParameter
    path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\application_parameter_py3.py
    remote:
      branch: master
      path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\application_parameter_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Describes an application parameter override to be applied when creating
    or

    upgrading an application.


    All required parameters must be populated in order to send to Azure.

    '
  syntax:
    content: 'ApplicationParameter(*, key: str, value: str, **kwargs) -> None'
    parameters:
    - description: 'Required. The name of the parameter.

        '
      id: key
      type:
      - str
    - description: 'Required. The value of the parameter.

        '
      id: value
      type:
      - str
  type: class
  uid: azure.mgmt.servicefabric.models.application_parameter_py3.ApplicationParameter
references: []
