### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.servicefabric.models.application_resource_update.ApplicationResourceUpdate
  fullName: azure.mgmt.servicefabric.models.application_resource_update
  langs:
  - python
  module: azure.mgmt.servicefabric.models.application_resource_update
  name: application_resource_update
  source:
    id: application_resource_update
    path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\application_resource_update.py
    remote:
      branch: master
      path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\application_resource_update.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.servicefabric.models.application_resource_update
references:
- fullName: azure.mgmt.servicefabric.models.application_resource_update.ApplicationResourceUpdate
  isExternal: false
  name: ApplicationResourceUpdate
  parent: azure.mgmt.servicefabric.models.application_resource_update
  uid: azure.mgmt.servicefabric.models.application_resource_update.ApplicationResourceUpdate
