### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.servicefabric.models.settings_section_description_py3.SettingsSectionDescription
  fullName: azure.mgmt.servicefabric.models.settings_section_description_py3
  langs:
  - python
  module: azure.mgmt.servicefabric.models.settings_section_description_py3
  name: settings_section_description_py3
  source:
    id: settings_section_description_py3
    path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\settings_section_description_py3.py
    remote:
      branch: master
      path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\settings_section_description_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.servicefabric.models.settings_section_description_py3
references:
- fullName: azure.mgmt.servicefabric.models.settings_section_description_py3.SettingsSectionDescription
  isExternal: false
  name: SettingsSectionDescription
  parent: azure.mgmt.servicefabric.models.settings_section_description_py3
  uid: azure.mgmt.servicefabric.models.settings_section_description_py3.SettingsSectionDescription
