### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.servicefabric.models.diagnostics_storage_account_config_py3.DiagnosticsStorageAccountConfig
  fullName: azure.mgmt.servicefabric.models.diagnostics_storage_account_config_py3
  langs:
  - python
  module: azure.mgmt.servicefabric.models.diagnostics_storage_account_config_py3
  name: diagnostics_storage_account_config_py3
  source:
    id: diagnostics_storage_account_config_py3
    path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\diagnostics_storage_account_config_py3.py
    remote:
      branch: master
      path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\diagnostics_storage_account_config_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.servicefabric.models.diagnostics_storage_account_config_py3
references:
- fullName: azure.mgmt.servicefabric.models.diagnostics_storage_account_config_py3.DiagnosticsStorageAccountConfig
  isExternal: false
  name: DiagnosticsStorageAccountConfig
  parent: azure.mgmt.servicefabric.models.diagnostics_storage_account_config_py3
  uid: azure.mgmt.servicefabric.models.diagnostics_storage_account_config_py3.DiagnosticsStorageAccountConfig
