### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.resource.managedapplications.application_client.ApplicationClient
  - azure.mgmt.resource.managedapplications.application_client.ApplicationClientConfiguration
  fullName: azure.mgmt.resource.managedapplications.application_client
  langs:
  - python
  module: azure.mgmt.resource.managedapplications.application_client
  name: application_client
  source:
    id: application_client
    path: azure-mgmt-resource\azure\mgmt\resource\managedapplications\application_client.py
    remote:
      branch: master
      path: azure-mgmt-resource\azure\mgmt\resource\managedapplications\application_client.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.resource.managedapplications.application_client
references:
- fullName: azure.mgmt.resource.managedapplications.application_client.ApplicationClient
  isExternal: false
  name: ApplicationClient
  parent: azure.mgmt.resource.managedapplications.application_client
  uid: azure.mgmt.resource.managedapplications.application_client.ApplicationClient
- fullName: azure.mgmt.resource.managedapplications.application_client.ApplicationClientConfiguration
  isExternal: false
  name: ApplicationClientConfiguration
  parent: azure.mgmt.resource.managedapplications.application_client
  uid: azure.mgmt.resource.managedapplications.application_client.ApplicationClientConfiguration
