### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.resource.resources.v2018_02_01.models.deployment_validate_result.DeploymentValidateResult
  fullName: azure.mgmt.resource.resources.v2018_02_01.models.deployment_validate_result.DeploymentValidateResult
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.resource.resources.v2018_02_01.models.deployment_validate_result
  name: DeploymentValidateResult
  source:
    id: DeploymentValidateResult
    path: azure-mgmt-resource\azure\mgmt\resource\resources\v2018_02_01\models\deployment_validate_result.py
    remote:
      branch: master
      path: azure-mgmt-resource\azure\mgmt\resource\resources\v2018_02_01\models\deployment_validate_result.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Information from validate template deployment response.

    '
  syntax:
    content: DeploymentValidateResult(**kwargs)
    parameters:
    - description: 'Validation error.

        '
      id: error
      type:
      - azure.mgmt.resource.resources.v2018_02_01.models.ResourceManagementErrorWithDetails
    - description: 'The template deployment properties.

        '
      id: properties
      type:
      - azure.mgmt.resource.resources.v2018_02_01.models.DeploymentPropertiesExtended
  type: class
  uid: azure.mgmt.resource.resources.v2018_02_01.models.deployment_validate_result.DeploymentValidateResult
references: []
