### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.resource.policy.v2016_12_01.policy_client.PolicyClientConfiguration
  fullName: azure.mgmt.resource.policy.v2016_12_01.policy_client.PolicyClientConfiguration
  inheritance:
  - inheritance:
    - inheritance:
      - type: builtins.object
      type: msrest.configuration.Configuration
    type: msrestazure.azure_configuration.AzureConfiguration
  langs:
  - python
  module: azure.mgmt.resource.policy.v2016_12_01.policy_client
  name: PolicyClientConfiguration
  source:
    id: PolicyClientConfiguration
    path: azure-mgmt-resource\azure\mgmt\resource\policy\v2016_12_01\policy_client.py
    remote:
      branch: master
      path: azure-mgmt-resource\azure\mgmt\resource\policy\v2016_12_01\policy_client.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 21
  summary: 'Configuration for PolicyClient

    Note that all parameters used to create this instance are saved as instance

    attributes.

    '
  syntax:
    content: PolicyClientConfiguration(credentials, subscription_id, base_url=None)
    parameters:
    - description: 'Credentials needed for the client to connect to Azure.

        '
      id: credentials
      type:
      - msrestazure.azure_active_directory
    - description: 'The ID of the target subscription.

        '
      id: subscription_id
      type:
      - str
    - description: 'Service URL

        '
      id: base_url
      type:
      - str
  type: class
  uid: azure.mgmt.resource.policy.v2016_12_01.policy_client.PolicyClientConfiguration
references: []
