### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.containerservice.models.container_service_ssh_configuration.ContainerServiceSshConfiguration
  fullName: azure.mgmt.containerservice.models.container_service_ssh_configuration
  langs:
  - python
  module: azure.mgmt.containerservice.models.container_service_ssh_configuration
  name: container_service_ssh_configuration
  source:
    id: container_service_ssh_configuration
    path: azure-mgmt-containerservice\azure\mgmt\containerservice\models\container_service_ssh_configuration.py
    remote:
      branch: master
      path: azure-mgmt-containerservice\azure\mgmt\containerservice\models\container_service_ssh_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.containerservice.models.container_service_ssh_configuration
references:
- fullName: azure.mgmt.containerservice.models.container_service_ssh_configuration.ContainerServiceSshConfiguration
  isExternal: false
  name: ContainerServiceSshConfiguration
  parent: azure.mgmt.containerservice.models.container_service_ssh_configuration
  uid: azure.mgmt.containerservice.models.container_service_ssh_configuration.ContainerServiceSshConfiguration
