### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.servicebus.models.migration_config_properties_py3.MigrationConfigProperties
  fullName: azure.mgmt.servicebus.models.migration_config_properties_py3.MigrationConfigProperties
  inheritance:
  - inheritance:
    - inheritance:
      - type: builtins.object
      type: msrest.serialization.Model
    type: azure.mgmt.servicebus.models.resource_py3.Resource
  langs:
  - python
  module: azure.mgmt.servicebus.models.migration_config_properties_py3
  name: MigrationConfigProperties
  source:
    id: MigrationConfigProperties
    path: azure-mgmt-servicebus\azure\mgmt\servicebus\models\migration_config_properties_py3.py
    remote:
      branch: master
      path: azure-mgmt-servicebus\azure\mgmt\servicebus\models\migration_config_properties_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Single item in List or Get Migration Config operation.


    Variables are only populated by the server, and will be ignored when

    sending a request.


    All required parameters must be populated in order to send to Azure.

    '
  syntax:
    content: 'MigrationConfigProperties(*, target_namespace: str, post_migration_name:
      str, **kwargs) -> None'
    parameters:
    - description: 'Required. Existing premium Namespace ARM Id name

        which has no entities, will be used for migration

        '
      id: target_namespace
      type:
      - str
    - description: 'Required. Name to access Standard Namespace

        after migration

        '
      id: post_migration_name
      type:
      - str
    variables:
    - description: 'Resource Id

        '
      id: id
      type:
      - str
    - description: 'Resource name

        '
      id: name
      type:
      - str
    - description: 'Resource type

        '
      id: type
      type:
      - str
    - description: 'Provisioning state of Migration Configuration

        '
      id: provisioning_state
      type:
      - str
    - description: 'Number of entities pending to

        be replicated.

        '
      id: pending_replication_operations_count
      type:
      - long
  type: class
  uid: azure.mgmt.servicebus.models.migration_config_properties_py3.MigrationConfigProperties
references: []
