### YamlMime:UniversalReference
api_name: []
items:
- children:
  - provisioningserviceclient.serviceswagger.models.x509_certificates.X509Certificates
  fullName: provisioningserviceclient.serviceswagger.models.x509_certificates
  langs:
  - python
  module: provisioningserviceclient.serviceswagger.models.x509_certificates
  name: x509_certificates
  source:
    id: x509_certificates
    path: provisioning_service_client\provisioningserviceclient\serviceswagger\models\x509_certificates.py
    remote:
      branch: master
      path: provisioning_service_client\provisioningserviceclient\serviceswagger\models\x509_certificates.py
      repo: https://github.com/Azure/azure-iot-sdk-python.git
    startLine: 0
  type: module
  uid: provisioningserviceclient.serviceswagger.models.x509_certificates
references:
- fullName: provisioningserviceclient.serviceswagger.models.x509_certificates.X509Certificates
  isExternal: false
  name: X509Certificates
  parent: provisioningserviceclient.serviceswagger.models.x509_certificates
  uid: provisioningserviceclient.serviceswagger.models.x509_certificates.X509Certificates
