### YamlMime:UniversalReference
api_name: []
items:
- children:
  - provisioningserviceclient.serviceswagger.operations.device_enrollment_group_operations.DeviceEnrollmentGroupOperations
  fullName: provisioningserviceclient.serviceswagger.operations.device_enrollment_group_operations
  langs:
  - python
  module: provisioningserviceclient.serviceswagger.operations.device_enrollment_group_operations
  name: device_enrollment_group_operations
  source:
    id: device_enrollment_group_operations
    path: provisioning_service_client\provisioningserviceclient\serviceswagger\operations\device_enrollment_group_operations.py
    remote:
      branch: master
      path: provisioning_service_client\provisioningserviceclient\serviceswagger\operations\device_enrollment_group_operations.py
      repo: https://github.com/Azure/azure-iot-sdk-python.git
    startLine: 0
  type: module
  uid: provisioningserviceclient.serviceswagger.operations.device_enrollment_group_operations
references:
- fullName: provisioningserviceclient.serviceswagger.operations.device_enrollment_group_operations.DeviceEnrollmentGroupOperations
  isExternal: false
  name: DeviceEnrollmentGroupOperations
  parent: provisioningserviceclient.serviceswagger.operations.device_enrollment_group_operations
  uid: provisioningserviceclient.serviceswagger.operations.device_enrollment_group_operations.DeviceEnrollmentGroupOperations
