### YamlMime:UniversalReference
api_name: []
items:
- children:
  - provisioningserviceclient.serviceswagger.models.x509_attestation.X509Attestation
  fullName: provisioningserviceclient.serviceswagger.models.x509_attestation
  langs:
  - python
  module: provisioningserviceclient.serviceswagger.models.x509_attestation
  name: x509_attestation
  source:
    id: x509_attestation
    path: provisioning_service_client\provisioningserviceclient\serviceswagger\models\x509_attestation.py
    remote:
      branch: master
      path: provisioning_service_client\provisioningserviceclient\serviceswagger\models\x509_attestation.py
      repo: https://github.com/Azure/azure-iot-sdk-python.git
    startLine: 0
  type: module
  uid: provisioningserviceclient.serviceswagger.models.x509_attestation
references:
- fullName: provisioningserviceclient.serviceswagger.models.x509_attestation.X509Attestation
  isExternal: false
  name: X509Attestation
  parent: provisioningserviceclient.serviceswagger.models.x509_attestation
  uid: provisioningserviceclient.serviceswagger.models.x509_attestation.X509Attestation
