### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.rdbms.mysql.models.configuration_paged.ConfigurationPaged
  fullName: azure.mgmt.rdbms.mysql.models.configuration_paged
  langs:
  - python
  module: azure.mgmt.rdbms.mysql.models.configuration_paged
  name: configuration_paged
  source:
    id: configuration_paged
    path: azure-mgmt-rdbms\azure\mgmt\rdbms\mysql\models\configuration_paged.py
    remote:
      branch: master
      path: azure-mgmt-rdbms\azure\mgmt\rdbms\mysql\models\configuration_paged.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.rdbms.mysql.models.configuration_paged
references:
- fullName: azure.mgmt.rdbms.mysql.models.configuration_paged.ConfigurationPaged
  isExternal: false
  name: ConfigurationPaged
  parent: azure.mgmt.rdbms.mysql.models.configuration_paged
  uid: azure.mgmt.rdbms.mysql.models.configuration_paged.ConfigurationPaged
