### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.servicefabric.models.application_health_report_created_event.ApplicationHealthReportCreatedEvent
  fullName: azure.servicefabric.models.application_health_report_created_event.ApplicationHealthReportCreatedEvent
  inheritance:
  - inheritance:
    - inheritance:
      - inheritance:
        - type: builtins.object
        type: msrest.serialization.Model
      type: azure.servicefabric.models.fabric_event.FabricEvent
    type: azure.servicefabric.models.application_event.ApplicationEvent
  langs:
  - python
  module: azure.servicefabric.models.application_health_report_created_event
  name: ApplicationHealthReportCreatedEvent
  source:
    id: ApplicationHealthReportCreatedEvent
    path: azure-servicefabric\azure\servicefabric\models\application_health_report_created_event.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\application_health_report_created_event.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Application Health Report Created event.


    All required parameters must be populated in order to send to Azure.

    '
  syntax:
    content: ApplicationHealthReportCreatedEvent(**kwargs)
    parameters:
    - description: 'Required. The identifier for the FabricEvent

        instance.

        '
      id: event_instance_id
      type:
      - str
    - description: 'Required. The time event was logged.

        '
      id: time_stamp
      type:
      - datetime
    - description: 'Shows there is existing related events

        available.

        '
      id: has_correlated_events
      type:
      - bool
    - description: 'Required. Constant filled by server.

        '
      id: kind
      type:
      - str
    - description: 'Required. The identity of the application. This is

        an encoded representation of the application name. This is used in the

        REST APIs to identify the application resource.

        Starting in version 6.0, hierarchical names are delimited with the "~"

        character. For example, if the application name is "fabric:/myapp/app1",

        the application identity would be "myapp~app1" in 6.0+ and "myapp/app1"

        in previous versions.

        '
      id: application_id
      type:
      - str
    - description: 'Required. Id of Application instance.

        '
      id: application_instance_id
      type:
      - long
    - description: 'Required. Id of report source.

        '
      id: source_id
      type:
      - str
    - description: 'Required. Describes the property.

        '
      id: property
      type:
      - str
    - description: 'Required. Describes the property health state.

        '
      id: health_state
      type:
      - str
    - description: 'Required. Time to live in milli-seconds.

        '
      id: time_to_live_ms
      type:
      - long
    - description: 'Required. Sequence number of report.

        '
      id: sequence_number
      type:
      - long
    - description: 'Required. Description of report.

        '
      id: description
      type:
      - str
    - description: 'Required. Indicates the removal when it

        expires.

        '
      id: remove_when_expired
      type:
      - bool
    - description: 'Required. Source time.

        '
      id: source_utc_timestamp
      type:
      - datetime
  type: class
  uid: azure.servicefabric.models.application_health_report_created_event.ApplicationHealthReportCreatedEvent
references: []
