### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation_error.BulkEnrollmentOperationError
  fullName: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation_error.BulkEnrollmentOperationError
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation_error
  name: BulkEnrollmentOperationError
  source:
    id: BulkEnrollmentOperationError
    path: provisioning_service_client\provisioningserviceclient\serviceswagger\models\bulk_enrollment_operation_error.py
    remote:
      branch: master
      path: provisioning_service_client\provisioningserviceclient\serviceswagger\models\bulk_enrollment_operation_error.py
      repo: https://github.com/Azure/azure-iot-sdk-python.git
    startLine: 11
  summary: 'Bulk enrollment operation error.

    '
  syntax:
    content: BulkEnrollmentOperationError(registration_id, error_code, error_status)
    parameters:
    - description: 'Device registration id.

        '
      id: registration_id
      type:
      - str
    - description: 'Error code

        '
      id: error_code
      type:
      - int
    - description: 'Error status

        '
      id: error_status
      type:
      - str
  type: class
  uid: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation_error.BulkEnrollmentOperationError
references: []
