### YamlMime:UniversalReference
api_name: []
items:
- children:
  - provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation.BulkEnrollmentOperation
  fullName: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation
  langs:
  - python
  module: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation
  name: bulk_enrollment_operation
  source:
    id: bulk_enrollment_operation
    path: provisioning_service_client\provisioningserviceclient\serviceswagger\models\bulk_enrollment_operation.py
    remote:
      branch: master
      path: provisioning_service_client\provisioningserviceclient\serviceswagger\models\bulk_enrollment_operation.py
      repo: https://github.com/Azure/azure-iot-sdk-python.git
    startLine: 0
  type: module
  uid: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation
references:
- fullName: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation.BulkEnrollmentOperation
  isExternal: false
  name: BulkEnrollmentOperation
  parent: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation
  uid: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation.BulkEnrollmentOperation
