### YamlMime:UniversalReference
api_name: []
items:
- children:
  - provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation_result.BulkEnrollmentOperationResult
  fullName: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation_result
  langs:
  - python
  module: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation_result
  name: bulk_enrollment_operation_result
  source:
    id: bulk_enrollment_operation_result
    path: provisioning_service_client\provisioningserviceclient\serviceswagger\models\bulk_enrollment_operation_result.py
    remote:
      branch: master
      path: provisioning_service_client\provisioningserviceclient\serviceswagger\models\bulk_enrollment_operation_result.py
      repo: https://github.com/Azure/azure-iot-sdk-python.git
    startLine: 0
  type: module
  uid: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation_result
references:
- fullName: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation_result.BulkEnrollmentOperationResult
  isExternal: false
  name: BulkEnrollmentOperationResult
  parent: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation_result
  uid: provisioningserviceclient.serviceswagger.models.bulk_enrollment_operation_result.BulkEnrollmentOperationResult
