### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.trafficmanager.models.monitor_config_expected_status_code_ranges_item_py3.MonitorConfigExpectedStatusCodeRangesItem
  fullName: azure.mgmt.trafficmanager.models.monitor_config_expected_status_code_ranges_item_py3.MonitorConfigExpectedStatusCodeRangesItem
  inheritance:
  - inheritance:
    - type: builtins.object
    type: msrest.serialization.Model
  langs:
  - python
  module: azure.mgmt.trafficmanager.models.monitor_config_expected_status_code_ranges_item_py3
  name: MonitorConfigExpectedStatusCodeRangesItem
  source:
    id: MonitorConfigExpectedStatusCodeRangesItem
    path: azure-mgmt-trafficmanager\azure\mgmt\trafficmanager\models\monitor_config_expected_status_code_ranges_item_py3.py
    remote:
      branch: master
      path: azure-mgmt-trafficmanager\azure\mgmt\trafficmanager\models\monitor_config_expected_status_code_ranges_item_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Min and max value of a status code range.

    '
  syntax:
    content: 'MonitorConfigExpectedStatusCodeRangesItem(*, min: int = None, max: int
      = None, **kwargs) -> None'
    parameters:
    - description: 'Min status code.

        '
      id: min
      type:
      - int
    - description: 'Max status code.

        '
      id: max
      type:
      - int
  type: class
  uid: azure.mgmt.trafficmanager.models.monitor_config_expected_status_code_ranges_item_py3.MonitorConfigExpectedStatusCodeRangesItem
references: []
